Fix if you have unload script and set build mode to release
danielkrupinski/GOESP pull request #55
Opened 2020-08-27 17:28 UTC by bruhmoment21

--no-gnu-unique allows unloading

2020-08-29 19:10 UTC, danielkrupinski requested changes

2020-08-29 19:10 UTC, danielkrupinski commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE RELEASE)
I wouldn't do that, because it makes impossible to set `CMAKE_BUILD_TYPE` from outside.

2020-08-30 06:24 UTC, bruhmoment21 commented
Ok so simply adding `set(CMAKE_CXX_FLAGS "--no-gnu-unique")` after `CMAKE_CXX_STANDARD` works fine.

2020-08-30 12:07 UTC, danielkrupinski approved these changes

2020-08-30 12:07 UTC, merged

2020-08-30 12:08 UTC, danielkrupinski commented
Thanks!